### ISSUE TITLE
Mismatch in 'Last Dental Visit' field input and database format

### ISSUE THREAD

**Issue by NiruNeilNix** [Zalderaan/dentsys#13]
On: Add Patient Record | Dental History | Last Dental Visit

Last Dental Visit accepts a string input from user, but in the database, the value is stored as a date format.

![Screenshot 2024-11-18 185508](https://github.com/user-attachments/assets/95a356a5-9cc3-4906-9576-314b643e09fc)

![image](https://github.com/user-attachments/assets/d05e45c2-125c-4aba-b806-0058e9e17758)

**Comment by NiruNeilNix** [comment]
Date Picker exists when editing Patient Record but doesn't during adding Patient Record 

Adding
![image](https://github.com/user-attachments/assets/88f55698-00a4-47e4-b22d-3991d5380714)

Editing
 ![image](https://github.com/user-attachments/assets/6cb80011-434e-416b-8275-b8a8273c34a4)

**Comment by Zalderaan** [comment]
fixed by eric
