### ISSUE TITLE
'Effective Date' can be passed off as a string 

### ISSUE THREAD

**Issue by NiruNeilNix** [Zalderaan/dentsys#29]
Effective Date can be passed off as a string 

Passing Effective Date as a string 
![Screenshot 2024-12-05 210307](https://github.com/user-attachments/assets/4960c250-87eb-4d62-ad50-dd673234be2b)

Results in
![image](https://github.com/user-attachments/assets/c7151cc7-b538-4e5e-98d7-95f10d75065f)

**Comment by Zalderaan** [comment]
noted, will work on it.

add and edit ba to?

**Comment by NiruNeilNix** [comment]
@Zalderaan Both. Another error I found is that hindi pwede iupdate ung Patient Record kapag inedit ung 'Effective Date'

**Comment by Zalderaan** [comment]
Working on the edit on effective date and dental visit rn

**Comment by Zalderaan** [comment]
done, made date pickers read only and fixed update bug. Made initial date into whatever the initial data is when updating
