### ISSUE TITLE
(REVISION) Remove 'Add Record' and 'Reports' on Navigation Bar

### ISSUE THREAD

**Issue by NiruNeilNix** [Zalderaan/dentsys#30]
Based on Revisions from our presentation, we should remove 'Add Records' and 'Reports' button on Navigation Bar

**Comment by Zalderaan** [comment]
@Eriiixxx wdyt bout this?

**Comment by Zalderaan** [comment]
@Eriiixxx prioritize this one first and I'll help in state management and data passing

**Comment by Zalderaan** [comment]
Also done, closing now
