### ISSUE TITLE
Issues found ( while testing after installation )

### ISSUE THREAD

**Issue by NiruNeilNix** [Zalderaan/dentsys#31]
1. Patient Record | Disease/Condition Section - When updating patient records bawal mag remove ng condition , but adding is functioning properly 

2. Effective Date and/or Latest Dental Visit - Bawal pumili ng date after the current date meanwhile pwede sya Latest Dental Visit

**Comment by NiruNeilNix** [comment]
Optional suggestion - Ung sa treatments/services maganda sana if ung pinaka recently added procedure is sa pinaka taas ng list mapupunta. Sa pinaka baba sya napupunta at the moment. Just in case lng baka kasi isipin nila hindi nag go through ung inadd nila

**Comment by Zalderaan** [comment]
@NiruNeilNix san specifically tong sa number 2?? Sa add/edit patient forms ba or sa add lang or something

**Comment by Zalderaan** [comment]
> Optional suggestion - Ung sa treatments/services maganda sana if ung pinaka recently added procedure is sa pinaka taas ng list mapupunta. Sa pinaka baba sya napupunta at the moment. Just in case lng baka kasi isipin nila hindi nag go through ung inadd nila

noted

**Comment by NiruNeilNix** [comment]
@Zalderaan Ung number 2 both sya

**Comment by Zalderaan** [comment]
@NiruNeilNix as of now fixed na sa, branch ko ung sa conditions, may na comment out lang dun kaya nag error hahaha

Working on no. 2 atm
