### ISSUE TITLE
(REVISION) Add a Dashboard 

### ISSUE THREAD

**Issue by NiruNeilNix** [Zalderaan/dentsys#34]
Based on the revisions given, we should add a dashboard that will greet the user upon login that displays 'Number of Patients' widget and other widgets that would be useful for the Dental Clinic

**Comment by NiruNeilNix** [comment]
@Zalderaan @Eriiixxx 
So far for the analytics on our dashboard I've thought of adding:
- Number of patients
- Most Common Procedure 
- Number of Services
- Patient Genders

Do you guys have any suggestions on what we could change? Are there other things we should add onto our dashboard? Should we visualize these datas using charts, plots, etc etc? I'd love to gain your insights on this matter

**Comment by Zalderaan** [comment]
Can you expound more on the genders and services count analytics? I'd like to know your vision on how they might be used for the system or what insights the users can get from them.

For your second question, yes as much as possible I think charts would be a great addition for our dashboard. Could you add flutter chart libraries in your resesrch tasks, @NiruNeilNix? Then let us know what you found and whether you think it's feasible considering our deadlines

**Comment by NiruNeilNix** [comment]
For 'Gender' analytics I don't really see much of a use unless we implement something else with it such as Gender Analytics by Service where they select a service to view the breakdown of patients by gender ( e.g., Teeth Cleaning: 60% Female, 40% Male ). We could also replace the 'Number of Services' with 'Monthly Income' What do you think, @Zalderaan @Eriiixxx ? Do you guys have suggestions on what else we could add?

I've done research on what Flutter libraries we could use for charts or data visualization and found two. 

 **'fl_chart'** - https://pub.dev/packages/fl_chart
 
 **'syncfuction_flutter_charts'** - https://pub.dev/packages/syncfusion_flutter_charts

**Comment by Zalderaan** [comment]
gj on the dashboard u did bro. Absolutely made liked it
