### ISSUE TITLE
(REVISION) Patient Records | ADD Patient Record

### ISSUE THREAD

**Issue by NiruNeilNix** [Zalderaan/dentsys#36]
**Revisions for Patient Records**

 - [x] Birth Date and Age computation on Edit Records doesn't work

- [x] Nullable Dates shouldn't display anything when Viewing Patient Records

- [x] Remove the "Latest Updated Patient" and "Latest Added Patient" Widgets

**ADD Patient Record**

- [x]  They don't like the current layout of our Add Patient Records Screen **(Scrollable)**

**Comment by Zalderaan** [comment]
@Eriiixxx handle mo yung paglilipat ng add patient record into the 'patient records' destination. Gawin mo nalang sigurong dialog din.

@NiruNeilNix after ng dialog, help moko or handle mo yung logic sa auto compute dun, transfer mo lang siguro or something.

then ako na bahala sa passing ng data sa child form or dialog once nagawa mona eric

**Comment by NiruNeilNix** [comment]
@Zalderaan  pinush ko na ung auto compute ng age for Editing Records sa branch na dentsys-revision

**Comment by Zalderaan** [comment]
done
